// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "serverUrl": string;
      "autoConvert": boolean;
      "skipIfExists": boolean;
      "pipeline": string;
      "doOcr": boolean;
      "forceOcr": boolean;
      "tableMode": string;
      "doFormulaEnrichment": boolean;
      "doCodeEnrichment": boolean;
      "doChartExtraction": boolean;
      "doPictureClassification": boolean;
      "vlmPreset": string;
      "doPictureDescription": boolean;
      "pictureDescriptionPreset": string;
      "ocrLang": string;
      "advancedJson": string;
      "useAsyncEndpoint": boolean;
      "asyncPollIntervalSec": number;
      "maxConcurrency": number;
      "addFrontmatter": boolean;
      "attachToItem": boolean;
      "exportFolderPath": string;
      "notifyOnComplete": boolean;
    };
  }
}
